version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      #Required for hot reload in some environments.
      - WATCHFILES_FORCE_POLLING=true 
